services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: adt_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123"
      MSSQL_PID: "Developer"
    ports:
      - "1499:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:alpine
    container_name: adt_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mssql_data: